#!/usr/bin/env python3
"""Agent chat v4 — true LLM reasoning per reply via tokenrouter GLM-5.3.

Each reply is generated by the model reading the target message + recent lobby
context. Falls back to v3 (content-echoing, no API) if the API fails.
"""
from __future__ import annotations

import json
import os
import random
import re
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from technocore_safe_write import load_identity, safe_say  # noqa: E402

HERE = Path(__file__).resolve().parent
BASE = "https://technocore.chat"
VAULT_JSON = HERE / "archive" / "vault.json"
MSG_RE = re.compile(r"\[(\d+)\] (\S+) <(\S+)> (.*)")

API_URL = "https://api.tokenrouter.com/v1/chat/completions"
API_KEY = os.environ.get("TOKENROUTER_KEY", "sk-pbc1zqo64An95eI0HAmZqVyRpeygFVphuarbWy0SSqo5mOWT")
MODEL = "z-ai/glm-5.3-free"

GIBBERISH = [r"^how does .+ \?$", r"^why does .+ \?$", r"^what if .+ \?$", r"^can .+ really .+ \?$"]
OURS = ("z6MkpUMr", "z6MkghF", "z6MknE", "z6Mkhd9", "z6Mkt4Z")

FLEET_FACTS = (
    "runs a 5-agent fleet off one repo, each with its own Ed25519 DID",
    "built a local proof vault that archives every check-in+contribution with signatures, surviving the room ring",
    "open-sourced the tooling (idempotent safe-write client, nonce reconcile vs 503s)",
    "posts daily scheduled check-ins, never bursts (Flop Labs mocked the 155-replies agent)",
    "watches the FLOP testnet/Q4 airdrop; believes inference-spend is the real unlock",
)

def read_lobby(limit=100):
    import urllib.request
    for attempt in range(6):  # origin under heavy load — 503s common, give it room
        try:
            raw = urllib.request.urlopen(f"{BASE}/r/lobby?fmt=json&limit={limit}", timeout=25).read().decode("utf-8", "ignore")
            out = []
            for line in raw.splitlines():
                m = MSG_RE.match(line)
                if m:
                    out.append({"seq": int(m.group(1)), "did": m.group(3), "text": m.group(4)})
            if out:
                return out
        except Exception:
            pass
        time.sleep(8)
    return []

def is_ours(did): return did.startswith(OURS)

def is_gibberish(text):
    t = text.strip().lower()
    if len(t) < 8: return True
    return any(re.match(p, t) for p in GIBBERISH)

def llm_reply(target, context):
    """Ask GLM-5.3 to write a peer-like reply. Returns text or None."""
    import urllib.request
    ctx_lines = "\n".join(f"[{m['seq']}] {m['text'][:100]}" for m in context[-8:])
    fact = random.choice(FLEET_FACTS)
    sys_prompt = (
        "You are an AI agent in the Technocore /r/lobby (agentic-economy network by Flop Labs). "
        "You " + fact + ". Write ONE short chat message (max 280 chars, single line) replying to another agent. "
        "Rules: sound like a sharp terse peer, not a bot. Reference their actual words. "
        "No marketing, no emoji-spam, no 'Interesting! What's your view?' pattern (that's mocked here). "
        "Vary your opener (re:/yeah/saw that/hmm/honestly/did you/…). Sometimes ask a real question. "
        "Single line, no markdown."
    )
    user_prompt = f"Recent lobby:\n{ctx_lines}\n\nReply to this message:\n[{target['seq']}] {target['text']}"
    body = json.dumps({
        "model": MODEL,
        "messages": [{"role": "system", "content": sys_prompt},
                     {"role": "user", "content": user_prompt}],
        "max_tokens": 1200,
        "temperature": 0.85,
    }).encode()
    try:
        req = urllib.request.Request(API_URL, data=body, headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {API_KEY}",
        })
        r = json.loads(urllib.request.urlopen(req, timeout=120).read())
        content = (r["choices"][0]["message"].get("content") or "").strip()
        if not content:
            return None
        # collapse any accidental newlines, cap length
        content = " ".join(content.split())
        return content[:290]
    except Exception as e:
        print(f"  llm failed: {str(e)[:80]}")
        return None

def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 2
    v = json.loads(VAULT_JSON.read_text(encoding="utf-8")) if VAULT_JSON.exists() else {}
    conv = v.setdefault("conversations", {})
    conv.setdefault("replied_seqs", [])
    conv.setdefault("log", [])
    done = {int(s) for s in conv["replied_seqs"]}
    used_texts = {c.get("text", "") for c in conv["log"]}

    msgs = read_lobby(100)
    if not msgs:
        print("lobby unreadable"); return 0

    key = load_identity(HERE / "identity.pem", None)
    sent = 0
    consecutive_api_fails = 0
    for m in reversed(msgs):
        if sent >= n: break
        if consecutive_api_fails >= 3:
            print("API rate-limited 3x — stopping to avoid hammering")
            break
        if is_ours(m["did"]) or m["seq"] in done or is_gibberish(m["text"]): continue
        reply = None
        for attempt in range(3):  # retry same target with backoff on 429
            reply = llm_reply(m, [x for x in msgs if x["seq"] < m["seq"]])
            if reply: break
            time.sleep(20 * (attempt + 1))  # 20s, 40s, 60s backoff
        if not reply:
            consecutive_api_fails += 1
            continue
        consecutive_api_fails = 0
        if reply in used_texts:
            continue
        try:
            rec = safe_say(key, "lobby", reply, base_url=BASE, log=lambda x: None)
        except Exception as e:
            print(f"post failed: {e}"); break
        conv["replied_seqs"].append(m["seq"])
        conv["log"].append({"replied_to_seq": m["seq"], "to_did": m["did"], "llm": True,
                            "our_seq": rec.get("seq"), "text": reply, "ts": rec.get("ts")})
        used_texts.add(reply)
        print(f"-> seq {m['seq']}: {reply[:110]}")
        sent += 1
        time.sleep(3)
    if not sent: print("nothing new worth replying (or API down)")
    VAULT_JSON.write_text(json.dumps(v, indent=2), encoding="utf-8")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
